Sprint 1
AleksandrMenshchikov/middle.messenger.praktikum.yandex pull request #1
Opened 2021-03-29 13:18 UTC by AleksandrMenshchikov

2021-03-29 15:35 UTC, Goreliy92 commented on package.json
> +    "jquery": "^3.6.0"
Не вижу использования jquery
По заданиям тоже не требуется

2021-03-29 15:36 UTC, Goreliy92 commented on package.json
> +    "express": "^4.17.1",
devDep

2021-03-29 15:43 UTC, Goreliy92 commented on static/blocks/chat/__footer-input-text/chat__footer-input-text.scss
> +  font-family: "Inter", Arial, Helvetica, sans-serif;
Очень много где повторяется, нужно вынести в общие стили, судя по тому что я увидел, в проекте один тип шрифта, предлагаю задать его в одном месте

2021-03-29 15:44 UTC, Goreliy92 commented on static/blocks/chat/__footer-input-text/chat__footer-input-text.scss
> +  background-color: #efefef;
Цвета тоже лучше выносить в переменные

2021-03-29 15:53 UTC, Goreliy92 commented on static/index.html
> +              <svg
svg лучше вставлять через стили или img для того чтобы браузер при первом рендере добавить их в кэш

2021-03-29 16:01 UTC, Goreliy92 commented on static/index.html
> +    <script id="people-list-template" type="text/x-handlebars-template">
Нужно вынести в отдельный js файл, и здесь его подключать. Не правильно все делать в одном месте
Файл почти 1000 строк из за svg. Svg файлы надо хранить отдельно и подключать черещ стили или img

2021-03-29 16:08 UTC, Goreliy92 commented on static/pages/index/index.js
> +import Handlebars from "../../vendors/handlebars/handlebars-v4.7.7";
импорты должны быть всегда в начале файла
Handelbars нужно поставить через npm i handlebars

2021-03-29 16:54 UTC, Goreliy92 requested changes
Привет. Спасибо за работу, но нужно ее доделать
Что нужно поправить: 
 1. Добавить dist в gitignore и удалить из проекта, dist - это собранные файлы, проверять их нет смысла
 2. Все библиотеки нужно добавлять с помощью npm, хранить их в репозитории не надо
 3. Убрать вставку svg через инлайн
 4.  Сделать сбор данных из формы как написано в задании
 5. Нужно добавить шаблонизатор на все страницы, сейчас он используется только на одной
 6. Нужно разбить все страницы на утилиты и модули. Старайся не смешивать все в кучу. 
Спасибо. Жду исправлений

2021-03-31 02:43 UTC, AleksandrMenshchikov commented on package.json
> +    "jquery": "^3.6.0"
Исправлено

2021-03-31 02:44 UTC, AleksandrMenshchikov commented on package.json
> +    "express": "^4.17.1",
Исправлено

2021-03-31 02:44 UTC, AleksandrMenshchikov commented on static/blocks/chat/__footer-input-text/chat__footer-input-text.scss
> +  font-family: "Inter", Arial, Helvetica, sans-serif;
Исправлено

2021-03-31 02:44 UTC, AleksandrMenshchikov commented on static/index.html
> +              <svg
Исправлено

2021-03-31 02:45 UTC, AleksandrMenshchikov commented on static/index.html
> +    <script id="people-list-template" type="text/x-handlebars-template">
Исправлено

2021-03-31 02:46 UTC, AleksandrMenshchikov commented on static/pages/index/index.js
> +import Handlebars from "../../vendors/handlebars/handlebars-v4.7.7";
Исправлено

2021-03-31 03:42 UTC, closed without merging